tests/test_nodes.vty: skip mgw ip lines
Skip these lines, as the format has changed in newer libosmo-mgcp-client
code. Fix for:

  Exception: Result mismatch:
  Mismatch:
  Expect:
  '  mgw local-ip A.B.C.D'
  Got:
  '  mgw local-ip (A.B.C.D|X:X::X:X)'

Change-Id: Ib2bb68fce9f7ab031ddb891ef269172679f8fe1a